"""add country dimension: user countries/category_weights, article/story about-countries, story_feedback

Revision ID: 926a0a0b755d
Revises: 1652a18837bb
Create Date: 2026-07-10 23:32:08.032080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '926a0a0b755d'
down_revision: Union[str, Sequence[str], None] = '1652a18837bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # note: autogenerate also proposed dropping ix_articles_embedding_hnsw -
    # same false positive as 1652a18837bb (raw SQL index, not in SQLAlchemy
    # metadata). Left out on purpose.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'story_id')
    )
    op.create_index(op.f('ix_story_feedback_story_id'), 'story_feedback', ['story_id'], unique=False)
    op.create_index(op.f('ix_story_feedback_user_id'), 'story_feedback', ['user_id'], unique=False)
    op.add_column('articles', sa.Column('mentioned_countries', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('stories', sa.Column('about_countries', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('countries', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('category_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'category_weights')
    op.drop_column('users', 'countries')
    op.drop_column('stories', 'about_countries')
    op.drop_column('articles', 'mentioned_countries')
    op.drop_index(op.f('ix_story_feedback_user_id'), table_name='story_feedback')
    op.drop_index(op.f('ix_story_feedback_story_id'), table_name='story_feedback')
    op.drop_table('story_feedback')
    # ### end Alembic commands ###
